package me.jjghali.grades.android.data.soap;

//----------------------------------------------------
//
// Generated by www.easywsdl.com
// Version: 4.5.6.0
//
// Created by Quasar Development at 19/06/2016
//
//---------------------------------------------------



public interface IServiceEvents
{
    void Starting();

    void Completed(OperationResult result);
}
